### ISSUE TITLE
Report not showing

### ISSUE THREAD

**Issue by mrhappyma** [manrueda/lighthouse-report-action#7]
Hey hi hello-

I can see that this repo hasn't been touched recently, but I guess it might not have needed to be. I wonder if I shall get a response...

Anyhoo I was hoping you could help me figure out why this is showing the action run log instead of the reported data. I thought I had everything right, I've even looked at other repos using this and the configuration looks similar. Could you please help me figure out what is wrong :flushed: 

The action thingy is right here: https://github.com/mrhappyma/userexedotme/runs/8181253093

**Comment by mrhappyma** [comment]
Hey @manrueda? Are you there?

**Comment by willryan-stemcell** [comment]
@mrhappyma Did you get this sorted out? I can't see the logs anymore. LMK if you're still having trouble and make a new run if you are :)

**Comment by mrhappyma** [comment]
I did not get it sorted out, but the project I was trying to use this with
is old and no longer being used at all.
